language: node_js
node_js:
  - 6
before_script:
  - npm install -g mocha
  - npm install -g istanbul
  - npm install -g eslint
  - npm install
script:
  - npm test
sudo: required
dist: trusty
