language: node_js
node_js:
  - 4.0
before_script:
  - npm install -g mocha
  - npm install -g istanbul
  - npm install -g eslint
  - npm install
script:
  - npm test
  - npm lint
sudo: required
dist: trusty
